In [1]:
%cd ../..

/home/eli/AnacondaProjects/surprisal_regression


In [2]:
import hydra
import math
from omegaconf import OmegaConf
import pyro
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
from src.models.components.linear_regression import TrialwiseLinearRegression
import src.eval as evaluation

In [4]:
with hydra.initialize(version_base="1.3", config_path="../../configs", job_name="eval"):
    cfg = hydra.compose(config_name="eval.yaml", overrides=["ckpt_path=/home/eli/AnacondaProjects/surprisal_regression/logs/train/runs/2025-03-13_12-53-00/checkpoints/last.ckpt", "data=synthetic_adaptation",
                        "model.importance.ablations=['surprise']"], return_hydra_config=True)
    hydra.core.hydra_config.HydraConfig.instance().set_config(cfg)
    _, objects = evaluation.evaluate(cfg)

[rank: 0] No logger configs found! Skipping...
[striatum:2679342] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.striatum.1000/jf.0/112328704/shared_mem_cuda_pool.striatum could be created.
[striatum:2679342] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at /home/eli/AnacondaProjects/surprisal_regression/logs/train/runs/2025-03-13_12-53-00/checkpoints/last.ckpt
/home/eli/miniforge3/envs/ephys/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:277: Be aware that when using `ckpt_path`, callbacks used to create the checkpoint need to be provided during `Trainer` instantiation. Please add the following callbacks: ["ModelCheckpoint{'monitor': 'val/loss', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}", "

Testing: |                                                                                                    …

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test/log_evidence     │     -17111.494140625      │
│         test/loss         │       49749.7265625       │
└───────────────────────────┴───────────────────────────┘

In [5]:
objects['model'].importance.angle_alpha

tensor([0.4986, 0.5014], grad_fn=<DivBackward0>)

In [6]:
(objects['model'].importance.repetition_q_loc, objects['model'].importance.repetition_q_log_scale.exp())

(Parameter containing:
 tensor([-0.9398], requires_grad=True),
 tensor([0.2814], grad_fn=<ExpBackward0>))

In [7]:
objects['model'].importance.selectivity_q_log_scale.exp()

tensor([1.3243, 2.9580], grad_fn=<ExpBackward0>)

In [8]:
log_bayes_factor = -36521.0546875 - (-17111.494140625)
log_bayes_factor

-19409.560546875