In [1]:
%cd ..

/home/eli/AnacondaProjects/surprisal_regression


In [2]:
import hydra
import math
from omegaconf import OmegaConf
import pyro
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
from src.models.components.linear_regression import TrialwiseLinearRegression
import src.eval as evaluation

In [4]:
with hydra.initialize(version_base="1.3", config_path="../configs", job_name="eval"):
    cfg = hydra.compose(config_name="eval.yaml", overrides=["ckpt_path=logs/train/runs/2025-03-11_15-35-46/checkpoints/last.ckpt", "data=synthetic_adaptation"],
                    return_hydra_config=True)
    hydra.core.hydra_config.HydraConfig.instance().set_config(cfg)
    _, objects = evaluation.evaluate(cfg)

/home/eli/miniforge3/envs/ephys/lib/python3.12/site-packages/lightning/pytorch/utilities/parsing.py:209: Attribute 'importance' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['importance'])`.
[rank: 0] No logger configs found! Skipping...
[striatum:2210119] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.striatum.1000/jf.0/2192900096/shared_mem_cuda_pool.striatum could be created.
[striatum:2210119] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at logs/train/runs/2025-03-11_15-35-46/checkpoints/last.ckpt
/home/eli/miniforge3/envs/ephys/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:277: Be aware that when using `ckpt_path`, callbacks used to 

Testing: |                                                                                                    …

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test/log_evidence     │     -27291.095703125      │
│         test/loss         │      30685.95703125       │
└───────────────────────────┴───────────────────────────┘

In [5]:
objects['model'].importance.angle_alpha

tensor([0.4688, 0.5312], grad_fn=<DivBackward0>)

In [6]:
(objects['model'].importance.repetition_q_loc, objects['model'].importance.repetition_q_log_scale.exp())

(Parameter containing:
 tensor([-1.0008], requires_grad=True),
 tensor([0.0387], grad_fn=<ExpBackward0>))

In [7]:
(objects['model'].importance.selectivity_q_loc, objects['model'].importance.selectivity_q_log_scale.exp())

(Parameter containing:
 tensor([ 0.0515, -0.2635], requires_grad=True),
 tensor([0.0927, 0.2062], grad_fn=<ExpBackward0>))

In [8]:
objects['model'].importance.surprise_q_log_scale.exp()

tensor([0.0749, 0.0671, 0.0465, 0.0451], grad_fn=<ExpBackward0>)