In [1]:
%cd ..

/home/eli/AnacondaProjects/surprisal_regression


In [2]:
import hydra
import math
from omegaconf import OmegaConf
import pyro
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
from src.models.components.linear_regression import TrialwiseLinearRegression
import src.eval as evaluation

In [4]:
with hydra.initialize(version_base="1.3", config_path="../configs", job_name="eval"):
    cfg = hydra.compose(config_name="eval.yaml", overrides=["ckpt_path=logs/train/runs/2025-03-04_19-15-18/checkpoints/last.ckpt", "data=synthetic"],
                    return_hydra_config=True)
    hydra.core.hydra_config.HydraConfig.instance().set_config(cfg)
    _, objects = evaluation.evaluate(cfg)

/home/eli/miniforge3/envs/ephys/lib/python3.12/site-packages/lightning/pytorch/utilities/parsing.py:209: Attribute 'importance' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['importance'])`.
[rank: 0] No logger configs found! Skipping...
[striatum:686002] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.striatum.1000/jf.0/1215365120/shared_mem_cuda_pool.striatum could be created.
[striatum:686002] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at logs/train/runs/2025-03-04_19-15-18/checkpoints/last.ckpt
/home/eli/miniforge3/envs/ephys/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:277: Be aware that when using `ckpt_path`, callbacks used to cr

Testing: |                                                                                                    …

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test/log_evidence     │    -2205.858642578125     │
│         test/loss         │     2495.67626953125      │
└───────────────────────────┴───────────────────────────┘

In [5]:
objects['model'].importance.log_scale

Parameter containing:
tensor(2.7726, requires_grad=True)

In [6]:
(objects['model'].importance.surprise_p_loc, objects['model'].importance.surprise_p_log_scale)

(Parameter containing:
 tensor([1.6697, 1.6417, 1.7677, 1.7581], requires_grad=True),
 Parameter containing:
 tensor([-1.7971, -1.7730, -1.8121, -1.7998], requires_grad=True))

In [7]:
(objects['model'].importance.adaptation_p_loc, objects['model'].importance.adaptation_p_log_scale)

(Parameter containing:
 tensor([0.4602], requires_grad=True),
 Parameter containing:
 tensor([-1.3365], requires_grad=True))